disabled_rules:
  - trailing_whitespace
#function_parameter_count:
#  warning: 10
#  error: 15
line_length:
  warning: 150
type_body_length:
  warning: 400
  error: 450
file_length:
  warning: 500
warning_threshold: 50
identifier_name:
  min_length:
    warning: 2
    error: 1
excluded:
  - Pods/
  - Frameworks/
